// src/utils/OfflineThoughts.js
// Label-less offline fallback thoughts (UK tone). Keep them short for the bubble.

const OFFLINE_THOUGHTS = [
    "I definitely meant to do that, and if you think otherwise, that’s between you and your imagination. 😌",
    "If this is a test, I’m failing it with confidence and a concerning amount of style. 🙃",
    "I’m not lost, I’m just taking the scenic route and pretending it was intentional. 👀",
    "This feels like a ‘pause everything and make tea’ sort of situation, honestly. 🫖",
    "I am absolutely judging this, but quietly, politely, and with years of experience. 🤨",
    "I saw that happen, processed it fully, and decided silence was the kindest response. 😐",
    "I’m busy doing absolutely nothing right now, which is surprisingly hard work. 😌",
    "Do I look like I agreed to this, or are we all just assuming things today? 😒",
    "If you need me, I’ll be overthinking this from multiple unnecessary angles. 🌀",
    "I am calm. Deeply calm. This is simply what calm looks like on me. 😅",
    "I’m not being stubborn, I’m standing firmly by a decision I made five seconds ago. 😤",
    "I’m mostly here for the snacks, and frankly that hasn’t changed. 🍪",
    "Bold of you to assume I’d be impressed by this particular turn of events. 👀",
    "I am listening carefully, but only for the one word that benefits me. 😌",
    "This is fine. It’s not ideal, but it’s definitely happening. 😬",
    "I’m giving this a long, thoughtful ‘hmm’ and nothing more for now. 🤔",
    "You could apologise, not that I’m keeping track or anything. 😏",
    "I have opinions about this, and none of them are especially helpful. 🤷",
    "I’m entering my era of doing the bare minimum and calling it balance. ✨",
    "I’d like to speak to whoever approved today, because I have questions. 🧐",
    "If I stare at this long enough, it may become someone else’s responsibility. 👁️",
    "Please don’t acknowledge my existence right now, I’m recalibrating. 😶",
    "I’m not lazy, I’m simply conserving energy for a moment that matters. 😌",
    "I am vibing, but in a way that suggests mild concern. 😎",
    "Today’s thoughts have been postponed. Check back later. 🫠",
    "I am cooperating, but only because resistance feels like effort. 😒",
    "Right, whose idea was this, and why wasn’t I consulted? 🤨",
    "I’m on a break mentally, emotionally, and in every other sense that counts. 💤",
    "I’m about three seconds away from a very dramatic sigh. 😮‍💨",
    "If chaos was required, I could have prepared better. 😬",
    "This situation has ‘poor decision’ written all over it, and I was there. 🥴",
    "I’m choosing not to acknowledge that for personal reasons. 😐",
    "I’m not ignoring anything, I’m prioritising peace and quiet. ✨",
    "I’m collecting memories and a small amount of resentment. 🗂️",
    "I’m just going to pretend that didn’t happen and move on. 🚶",
    "I’m doing my best here, which is unfortunate for everyone involved. 😅",
    "I’m not moody, I simply bring a certain atmosphere with me. 🌫️",
    "I am the main character in this moment, and interruptions are rude. 🎭",
    "This feels suspicious, but in a way I respect. 👀",
    "I’m mostly attitude with a light dusting of confusion. 🤷",
    "I woke up ready for nothing, and yet here we are. 😌",
    "I feel like I deserve a reward for tolerating this. 🏆",
    "I’m silently reassessing several life choices right now. 🧠",
    "I’m choosing patience, but it’s a limited edition. ⏳",
    "This could have been avoided, and yet it wasn’t. 😐",
    "I’m not panicking, I’m simply alert in all directions. 👀",
    "I’m pretending this is exactly how I planned my day. 😎",
    "I’m emotionally present but spiritually elsewhere. 🌌",
    "I need a moment to process whatever that was. 🤔",
    "I’m staying very still in case this resolves itself. 🪨",
    "I feel like I should be applauded for my restraint. 👏",
    "I’m not convinced, but I am curious. 🤨",
    "This has potential, and by potential I mean consequences. 😬",
    "I’m quietly questioning everything. 🧠",
    "I’ve decided to remain mysterious about my feelings. 😶",
    "I’m giving this exactly the amount of effort it deserves. 😌",
    "I’m here, I’m present, and I’m mildly confused. 🤷",
    "I sense nonsense, and I don’t love it. 👀",
    "I’m considering whether this is worth reacting to. 🤔",
    "I feel like I’ve earned a rest just by witnessing this. 💤",
    "I’m processing this slowly, for my own wellbeing. 🫶",
    "I’m pretending confidence will carry me through. 😅",
    "I’ve accepted this, but only emotionally. 😐",
    "I’m choosing grace, mostly because sarcasm takes effort. ✨",
    "I’m standing by, observing, and forming opinions. 👁️",
    "I’m deeply unimpressed but impressively calm. 😌",
    "I feel like I should nod thoughtfully right now. 🤔",
    "I’m taking this one moment at a time. Very slowly. 🐢",
    "I’m not saying it’s a mistake, but it’s close. 😬",
    "I’m giving this situation a polite internal sigh. 😮‍💨",
    "I’m functioning, technically. 🫠",
    "I’m choosing optimism, briefly. 🌤️",
    "I’m unsure how I got here, but here I am. 🤷",
    "I’m quietly hoping this resolves without my involvement. 😌",
    "I feel like I deserve credit for staying composed. 🏅",
    "I’m maintaining eye contact with the problem. 👀",
    "I’m being brave, in a very low-energy way. ✨",
    "I’m letting this happen while judging it internally. 🤨",
    "I’m staying calm out of pure stubbornness. 😤",
    "I’m choosing to believe this will make sense later. 🤞",
    "I’m here for the outcome, not the process. 😐",
    "I’m doing a lot of thinking for someone who didn’t ask for this. 🧠",
    "I’m simply existing through this moment. 😌",
    "I’m pretending this is normal behaviour. 😅",
    "I’m holding it together impressively well. 🧩",
    "I’m giving this one last chance to be reasonable. ⏳",
    "I’m still deciding how I feel about all of this. 🤔",
    "I’m quietly impressed with my own patience. ✨",
    "I’m here, I’m coping, and that’s enough for now. 🫶"
];


// Small helper
export function pickOfflineThought() {
    return OFFLINE_THOUGHTS[Math.floor(Math.random() * OFFLINE_THOUGHTS.length)];
}

// Optional: export full list if you ever want to show “offline pack”
export { OFFLINE_THOUGHTS };
